# Generated by Django 5.2.3 on 2025-07-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_password', models.CharField(max_length=16)),
                ('room_is_private', models.BooleanField()),
                ('room_max_people', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('uid', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
